app_login:  
    path: /Login
    controller: App\Controller\loginController::index

debut_intervenant:
    path: /Intervenant/Prise_vehicule
    controller: App\Controller\IntervenantDebutController::debut

fin_intervenant:
    path: /Intervenant/Retour_vehicule
    controller: App\Controller\IntervenantFinController::fin

logout:
    path: /logout
    controller: App\Controller\LogoutController::index


controllers:
    resource: ../src/Controller/
    type: attribute
